#!/bin/bash

# Copyright 2015 Nordstrom, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o errexit -o nounset -o pipefail

# If the user has not passed in a cookbook name use 'pd_devops_bootstrap' for the cookbook
bootstrapCookbook=${1:-pd_devops_bootstrap}

# If the user has passed in a private supermarket url then add it to the Berksfile
private_source=${2:+source '$2'}

# make userChefDir variable
userChefDir=~/chef

clear

# introduction
cat <<EOF
This script will:

1. Install the latest Chef Workstation package
2. Install git
3. Create a 'chef' directory in your user profile (home) directory
4. Download the 'pd_devops_bootstrap' cookbook via Berkshelf
5. Run 'chef-client' to install the rest of the tools you will need
EOF

if [[ ! -f /etc/yum.conf.bak ]] && [[ ! -z ${http_proxy+x} ]] ; then
  echo "Adding proxy to /etc/yum.conf"
  sudo cp /etc/yum.conf /etc/yum.conf.bak
  echo "proxy=$http_proxy" | sudo tee --append /etc/yum.conf
fi

if [[ ! -f /etc/environments.bak ]] && [[ ! -z ${http_proxy+x} ]] ; then
  echo "Adding proxy to /etc/environment"
  sudo cp /etc/environment /etc/environment.bak
  echo "proxy=$http_proxy" | sudo tee --append /etc/environment
fi

# creating a Chef directory for Chef development
if [ ! -d "${userChefDir}" ] ; then
  mkdir "${userChefDir}"
fi

# creating a berks config
if [ ! -d ~/.berkshelf ] ; then
  mkdir ~/.berkshelf
fi

cat > ~/.berkshelf/config.json <<EOF
{"ssl":{"verify": false }}
EOF

# create Berksfile so that we can install the correct cookbook dependencies
cat > "${userChefDir}/Berksfile" <<EOF
source 'https://supermarket.chef.io'
"${private_source}"

cookbook '${bootstrapCookbook}', git: 'https://github.com/daxgames/pd_devops_bootstrap.git'
EOF

# create client.rb file so that Chef client can find its dependant cookbooks
cat > "${userChefDir}/client.rb" <<EOF
cookbook_path File.join(Dir.pwd, 'berks-cookbooks')
EOF

# # # install chef-workstation
# cd "${userChefDir}"
# export PD_SW_CHEFWS_VER=0.3.2
# 
# # no need to download more than once while testing
# new_download=0
# if [ ! -f chef_workstation_${PD_SW_CHEFWS_VER}.rpm ] ; then
#   echo Downlaoding Chef Workstation...
#   curl http://packages.chef.io/files/stable/chef-workstation/${PD_SW_CHEFWS_VER}/el/7/chef-workstation-${PD_SW_CHEFWS_VER}-1.el6.x86_64.rpm > chef_workstation_${PD_SW_CHEFWS_VER}.rpm
#   new_download=1
# fi
# 
# if [ ! -d /opt/chef-workstation ] || [ "${new_download}" == "1" ] ; then
#   echo Installing Chef Workstation...
#   sudo rpm -Uvh chef_workstation_${PD_SW_CHEFWS_VER}.rpm
# fi

echo Installing Chef Workstation...
curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 0.3.2 -P chef-workstation

# chef needs git installed to pull down cookbooks
# sudo yum -y update --exclude=stub-redhat-lsb-core-only-for-ceph-2015.1-1.atomic.el7.noarch
sudo yum -y update --exclude=stub-redhat-lsb-core-only-for-ceph
sudo yum -y install git

# making sure that we are vendor cookbooks into a sub directory of the userChefDir
if [ -f $HOME/chef/Berksfile.lock ] ; then
  rm Berksfile.lock
fi
berks vendor

# run chef-client (installed by Chef Workstation) to bootstrap this machine
sudo -E chef-client -z -l error -c "${userChefDir}/client.rb" -o "pd_devops_bootstrap::default,$PD_DEVOPS_BOOTSTRAP_SELECTIONS"

# cleanup
[[ -f "${userChefDir}/berksfile" ]] && rm "${userChefDir}/berksfile"
[[ -f "${userChefDir}/chef_workstation_${PD_SW_CHEFWS_VER}.rpm" ]] && rm "${userChefDir}/chef_workstation_${PD_SW_CHEFWS_VER}.rpm"
[[ -f "${userChefDir}/Berksfile.lock" ]] && rm "${userChefDir}/Berksfile.lock"
[[ -f "${userChefDir}/client.rb" ]] && rm "${userChefDir}/client.rb"
[[ -d berks-cookbooks ]] && rm -r berks-cookbooks

if [[ -f /etc/yum.conf.bak ]] && [[ ! -z ${http_proxy+x} ]] ; then
  sudo mv /etc/yum.conf.bak /etc/yum.conf
fi

if [[ -f /etc/environment.bak ]] && [[ ! -z ${http_proxy+x} ]]; then
  sudo mv /etc/environment.bak /etc/environments.bak
fi

#End message to direct CentOS RHEL users to last step in set up
cat <<EOF
You're almost done!!! Go back to the pd_devops_bootstrap README to complete your Chef workstation setup.
EOF
