#!/bin/bash

# Copyright 2015 Nordstrom, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -o errexit -o nounset -o pipefail

# If the user has not passed in a cookbook name use 'pd_devops_bootstrap' for the cookbook
bootstrapCookbook=${1:-pd_devops_bootstrap}

# If the user has passed in a private supermarket url then add it to the Berksfile
private_source=${2:+source '$2'}

# make userChefDir variable
userChefDir=~/chef

clear

# introduction
cat <<EOF
This script will:

1. Install the latest Chef Workstation package
2. Install git
3. Create a 'chef' directory in your user profile (home) directory
4. Download the 'pd_devops_bootstrap' cookbook via Berkshelf
5. Run 'chef-client' to install the rest of the tools you will need
EOF

# creating a Chef directory for Chef development
if [ ! -d "${userChefDir}" ] ; then
  mkdir "${userChefDir}"
fi

# creating a berks config
if [ ! -d ~/.berkshelf ] ; then
  mkdir ~/.berkshelf
fi

cat > ~/.berkshelf/config.json <<EOF
{"ssl":{"verify": false }}
EOF

# create Berksfile so that we can install the correct cookbook dependencies
cat > "${userChefDir}/Berksfile" <<EOF
source 'https://supermarket.chef.io'
"${private_source}"

cookbook '${bootstrapCookbook}', git: 'https://github.bedbath.com/pipedream/pd_devops_bootstrap.git'
EOF

# create client.rb file so that Chef client can find its dependant cookbooks
cat > "${userChefDir}/client.rb" <<EOF
cookbook_path File.join(Dir.pwd, 'berks-cookbooks')
EOF


# install chef-workstation
cd "${userChefDir}"
# no need to download more than once while testing
PD_SW_CHEFWS_VER=0.3.2
ubuntu_ver=$(lsb_release -r | awk '{print $NF}')
if [ ! -f chef_workstation_${PD_SW_CHEFWS_VER}.deb ] ; then
  echo curl https://packages.chef.io/files/stable/chef-workstation/${PD_SW_CHEFWS_VER}/ubuntu/${ubuntu_ver}/chef-workstation_${PD_SW_CHEFWS_VER}-1_amd64.deb > chef_workstation_${chef_workstation_ver}.deb
  curl https://packages.chef.io/files/stable/chef-workstation/${PD_SW_CHEFWS_VER}/ubuntu/${ubuntu_ver}/chef-workstation_${PD_SW_CHEFWS_VER}-1_amd64.deb > chef_workstation_${chef_workstation_ver}.deb
  new_download=1
fi

if [ ! -d /opt/chef_workstation ] || [ "${new_download}" == "1" ] ; then
  sudo dpkg -i chef_workstation_${chef_workstation_ver}.deb
fi

# chef needs git installed to pull down cookbooks
sudo apt-get update --yes
sudo apt-get install --yes git

# making sure that we are vendor cookbooks into a sub directory of the userChefDir
berks vendor

# run chef-client (installed by Chef Workstation) to bootstrap this machine
sudo -E chef-client -z -l error -c "${userChefDir}/client.rb" -o "$PD_DEVOPS_BOOTSTRAP_SELECTIONS"

# cleanup
[[ -f "${userChefDir}/berksfile" ]] && rm "${userChefDir}/berksfile"
[[ -f "${userChefDir}/chef_workstationi_${PD_SW_CHEFWS_VER}.deb" ]] && rm "${userChefDir}/chef_workstation_${PD_SW_CHEFWS_VER}.deb"
[[ -f "${userChefDir}/Berksfile.lock" ]] && rm "${userChefDir}/Berksfile.lock"
[[ -f "${userChefDir}/client.rb" ]] && rm "${userChefDir}/client.rb"
[[ -d berks-cookbooks ]] && rm -r berks-cookbooks

#End message to direct Ubuntu users to last step in set up
cat <<EOF
You're almost done!!! Go back to the pd_devops_bootstrap README to complete your Chef workstation setup.
EOF
