name 'pd_devops_bootstrap'
maintainer 'BBB Devops Engineering'
maintainer_email 'devops-eng@bedbath.com'
license 'all_rights'
description 'Installs/Configures pd_devops_bootstrap'
long_description 'Installs/Configures pd_devops_bootstrap'
version '0.2.4'

supports 'mac_os_x'
supports 'windows'
supports 'ubuntu'
supports 'centos'
supports 'redhat'

depends 'chocolatey'
depends 'git'
depends 'homebrew'
depends 'windows'
depends 'apt'
depends 'yum'
