name 'pd_pd_devops_bootstrap'
maintainer 'BBB Devops Engineering'
maintainer_email 'devops-eng@bedbath.com'
license 'all_rights'
description 'Installs/Configures pd_devops_bootstrap'
long_description 'Installs/Configures pd_devops_bootstrap'
version '0.2.4'

supports 'mac_os_x'
supports 'windows'
supports 'ubuntu'
supports 'centos'
supports 'redhat'

depends 'chocolatey', '~> 1.0.0'
depends 'git'       , '~> 5.0.1'
depends 'homebrew'  , '~> 1.13'
depends 'windows'   , '~> 2.0.0'
depends 'apt'       , '~> 2.9.2'
depends 'yum'       , '~> 3.8.2'
